//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooruDatasetTagManager {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BooruDatasetTagManager.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add tag 的本地化字符串。
        /// </summary>
        internal static string addtag_form_Title {
            get {
                return ResourceManager.GetString("addtag.form.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag 的本地化字符串。
        /// </summary>
        internal static string addtag_label1_Text {
            get {
                return ResourceManager.GetString("addtag.label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adding position 的本地化字符串。
        /// </summary>
        internal static string addtag_label2_Text {
            get {
                return ResourceManager.GetString("addtag.label2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string cancel_button_Text {
            get {
                return ResourceManager.GetString("cancel.button.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        internal static string edit_form_Title {
            get {
                return ResourceManager.GetString("edit.form.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        internal static string fileToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("fileToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All tags filter 的本地化字符串。
        /// </summary>
        internal static string filter_form_Title {
            get {
                return ResourceManager.GetString("filter.form.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter text 的本地化字符串。
        /// </summary>
        internal static string filter_label1_Text {
            get {
                return ResourceManager.GetString("filter.label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dataset 的本地化字符串。
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image tags 的本地化字符串。
        /// </summary>
        internal static string label2_Text {
            get {
                return ResourceManager.GetString("label2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Common tags 的本地化字符串。
        /// </summary>
        internal static string label3_commontags_Text {
            get {
                return ResourceManager.GetString("label3.commontags.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All tags 的本地化字符串。
        /// </summary>
        internal static string label3_Text {
            get {
                return ResourceManager.GetString("label3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load loss from file 的本地化字符串。
        /// </summary>
        internal static string loadLossFromFileToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("loadLossFromFileToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string ok_button_Text {
            get {
                return ResourceManager.GetString("ok.button.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load folder... 的本地化字符串。
        /// </summary>
        internal static string openFolderToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("openFolderToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview 的本地化字符串。
        /// </summary>
        internal static string preview_form_Title {
            get {
                return ResourceManager.GetString("preview.form.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace all 的本地化字符串。
        /// </summary>
        internal static string replace_form_Title {
            get {
                return ResourceManager.GetString("replace.form.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source tag 的本地化字符串。
        /// </summary>
        internal static string replace_label1_Text {
            get {
                return ResourceManager.GetString("replace.label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New tag 的本地化字符串。
        /// </summary>
        internal static string replace_label2_Text {
            get {
                return ResourceManager.GetString("replace.label2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save all changes 的本地化字符串。
        /// </summary>
        internal static string saveAllChangesToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("saveAllChangesToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string setting_button1_Text {
            get {
                return ResourceManager.GetString("setting.button1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string setting_button2_Text {
            get {
                return ResourceManager.GetString("setting.button2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change... 的本地化字符串。
        /// </summary>
        internal static string setting_button3_Text {
            get {
                return ResourceManager.GetString("setting.button3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change... 的本地化字符串。
        /// </summary>
        internal static string setting_button4_Text {
            get {
                return ResourceManager.GetString("setting.button4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load only manual translations into autocomplete 的本地化字符串。
        /// </summary>
        internal static string setting_checkBox1_Text {
            get {
                return ResourceManager.GetString("setting.checkBox1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fix tags on loading (replace &apos;_&apos; -&gt; &apos; &apos;) 的本地化字符串。
        /// </summary>
        internal static string setting_checkBox2_Text {
            get {
                return ResourceManager.GetString("setting.checkBox2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompt to save changes when changing selection 的本地化字符串。
        /// </summary>
        internal static string setting_checkBox3_Text {
            get {
                return ResourceManager.GetString("setting.checkBox3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fix tags on saving (&apos;(&apos;-&gt;&apos;\\(&apos;, &apos;)&apos;-&gt;&apos;\\)&apos; ) 的本地化字符串。
        /// </summary>
        internal static string setting_checkBox4_Text {
            get {
                return ResourceManager.GetString("setting.checkBox4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string setting_form_Title {
            get {
                return ResourceManager.GetString("setting.form.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation language 的本地化字符串。
        /// </summary>
        internal static string setting_label1_Text {
            get {
                return ResourceManager.GetString("setting.label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tags gridview font 的本地化字符串。
        /// </summary>
        internal static string setting_label10_Text {
            get {
                return ResourceManager.GetString("setting.label10.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tags gridview row height 的本地化字符串。
        /// </summary>
        internal static string setting_label12_Text {
            get {
                return ResourceManager.GetString("setting.label12.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Autocomplete font 的本地化字符串。
        /// </summary>
        internal static string setting_label13_Text {
            get {
                return ResourceManager.GetString("setting.label13.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview image size 的本地化字符串。
        /// </summary>
        internal static string setting_label2_Text {
            get {
                return ResourceManager.GetString("setting.label2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation service 的本地化字符串。
        /// </summary>
        internal static string setting_label3_Text {
            get {
                return ResourceManager.GetString("setting.label3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Autocomplete mode 的本地化字符串。
        /// </summary>
        internal static string setting_label4_Text {
            get {
                return ResourceManager.GetString("setting.label4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Autocomplete sort 的本地化字符串。
        /// </summary>
        internal static string setting_label5_Text {
            get {
                return ResourceManager.GetString("setting.label5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Separator on load 的本地化字符串。
        /// </summary>
        internal static string setting_label6_Text {
            get {
                return ResourceManager.GetString("setting.label6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Separator on save 的本地化字符串。
        /// </summary>
        internal static string setting_label7_Text {
            get {
                return ResourceManager.GetString("setting.label7.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show autocomplete after 的本地化字符串。
        /// </summary>
        internal static string setting_label8_Text {
            get {
                return ResourceManager.GetString("setting.label8.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chars 的本地化字符串。
        /// </summary>
        internal static string setting_label9_Text {
            get {
                return ResourceManager.GetString("setting.label9.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must restart the application for the settings to take effect. 的本地化字符串。
        /// </summary>
        internal static string setting_save_msg {
            get {
                return ResourceManager.GetString("setting.save.msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        internal static string setting_tabPage1_Text {
            get {
                return ResourceManager.GetString("setting.tabPage1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translations 的本地化字符串。
        /// </summary>
        internal static string setting_tabPage2_Text {
            get {
                return ResourceManager.GetString("setting.tabPage2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UI 的本地化字符串。
        /// </summary>
        internal static string setting_tabPage3_Text {
            get {
                return ResourceManager.GetString("setting.tabPage3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings... 的本地化字符串。
        /// </summary>
        internal static string settingsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("settingsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show preview 的本地化字符串。
        /// </summary>
        internal static string showPreviewToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("showPreviewToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete the selected image file? 的本地化字符串。
        /// </summary>
        internal static string tip_askDelete {
            get {
                return ResourceManager.GetString("tip.askDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete File 的本地化字符串。
        /// </summary>
        internal static string tip_askDelete_Title {
            get {
                return ResourceManager.GetString("tip.askDelete.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select at least one image 的本地化字符串。
        /// </summary>
        internal static string tip_atLeastOneImage {
            get {
                return ResourceManager.GetString("tip.atLeastOneImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dataset not load 的本地化字符串。
        /// </summary>
        internal static string tip_dataset_not_load {
            get {
                return ResourceManager.GetString("tip.dataset.not.load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current operate does not support multiple selection.  的本地化字符串。
        /// </summary>
        internal static string tip_doesNotSupportMultipleSelection {
            get {
                return ResourceManager.GetString("tip.doesNotSupportMultipleSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image name must be filled! 的本地化字符串。
        /// </summary>
        internal static string tip_imageMustBeFilled {
            get {
                return ResourceManager.GetString("tip.imageMustBeFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate request timeout 的本地化字符串。
        /// </summary>
        internal static string tip_requestTimeOut {
            get {
                return ResourceManager.GetString("tip.requestTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The dataset has been changed,\ndo you want to save the changes? 的本地化字符串。
        /// </summary>
        internal static string tip_saveDataSetChange {
            get {
                return ResourceManager.GetString("tip.saveDataSetChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saving changes 的本地化字符串。
        /// </summary>
        internal static string tip_saveDataSetChange_Title {
            get {
                return ResourceManager.GetString("tip.saveDataSetChange.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set tag list to empty images only?\nYes - only empty, No - to all images, Cancel - do nothing. 的本地化字符串。
        /// </summary>
        internal static string tip_SetTagListToEmptyImagesOnly {
            get {
                return ResourceManager.GetString("tip.SetTagListToEmptyImagesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag setting option 的本地化字符串。
        /// </summary>
        internal static string tip_SetTagListToEmptyImagesOnly_Title {
            get {
                return ResourceManager.GetString("tip.SetTagListToEmptyImagesOnly.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please wait while the tags are loading.\nWhen changing csv or txt files,\nthe initial loading of tags may take a long time. 的本地化字符串。
        /// </summary>
        internal static string tip_startUpLoadingMsg {
            get {
                return ResourceManager.GetString("tip.startUpLoadingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate finished 的本地化字符串。
        /// </summary>
        internal static string tip_statusLabel_Translated {
            get {
                return ResourceManager.GetString("tip.statusLabel.Translated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translating... 的本地化字符串。
        /// </summary>
        internal static string tip_statusLabel_Translating {
            get {
                return ResourceManager.GetString("tip.statusLabel.Translating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images or tags not selected! 的本地化字符串。
        /// </summary>
        internal static string tip_statusLabelImagesOrTagsNotSelected {
            get {
                return ResourceManager.GetString("tip.statusLabelImagesOrTagsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings have been saved 的本地化字符串。
        /// </summary>
        internal static string tip_statusLabelSettingsHaveBeenSaved {
            get {
                return ResourceManager.GetString("tip.statusLabelSettingsHaveBeenSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of selected images is not equal to 1 的本地化字符串。
        /// </summary>
        internal static string tip_statusLabelTheNumberOfSelectedImagesIsNotEqualTo1 {
            get {
                return ResourceManager.GetString("tip.statusLabelTheNumberOfSelectedImagesIsNotEqualTo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of selected images must be greater than 0 的本地化字符串。
        /// </summary>
        internal static string tip_statusLabelTheNumberOfSelectedImagesMustBeGreaterThan0 {
            get {
                return ResourceManager.GetString("tip.statusLabelTheNumberOfSelectedImagesMustBeGreaterThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of selected images must be greater than 1 的本地化字符串。
        /// </summary>
        internal static string tip_statusLabelTheNumberOfSelectedImagesMustBeGreaterThan1 {
            get {
                return ResourceManager.GetString("tip.statusLabelTheNumberOfSelectedImagesMustBeGreaterThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        internal static string toolStripButton1_Text {
            get {
                return ResourceManager.GetString("toolStripButton1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste tags 的本地化字符串。
        /// </summary>
        internal static string toolStripButton10_Text {
            get {
                return ResourceManager.GetString("toolStripButton10.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string toolStripButton11_Text {
            get {
                return ResourceManager.GetString("toolStripButton11.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove from all 的本地化字符串。
        /// </summary>
        internal static string toolStripButton12_Text {
            get {
                return ResourceManager.GetString("toolStripButton12.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find in dataset 的本地化字符串。
        /// </summary>
        internal static string toolStripButton13_Text {
            get {
                return ResourceManager.GetString("toolStripButton13.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset filter 的本地化字符串。
        /// </summary>
        internal static string toolStripButton14_Text {
            get {
                return ResourceManager.GetString("toolStripButton14.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste from clipboard 的本地化字符串。
        /// </summary>
        internal static string toolStripButton15_Text {
            get {
                return ResourceManager.GetString("toolStripButton15.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show formed tag text 的本地化字符串。
        /// </summary>
        internal static string toolStripButton16_Text {
            get {
                return ResourceManager.GetString("toolStripButton16.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set current tag list to all 的本地化字符串。
        /// </summary>
        internal static string toolStripButton17_Text {
            get {
                return ResourceManager.GetString("toolStripButton17.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multi-tag filtering mode 的本地化字符串。
        /// </summary>
        internal static string toolStripButton18_Text {
            get {
                return ResourceManager.GetString("toolStripButton18.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add selected &apos;All tags&apos; to image tags 的本地化字符串。
        /// </summary>
        internal static string toolStripButton19_Text {
            get {
                return ResourceManager.GetString("toolStripButton19.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string toolStripButton2_Text {
            get {
                return ResourceManager.GetString("toolStripButton2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove selected &apos;All tags&apos; from image tags 的本地化字符串。
        /// </summary>
        internal static string toolStripButton20_Text {
            get {
                return ResourceManager.GetString("toolStripButton20.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add to filtered 的本地化字符串。
        /// </summary>
        internal static string toolStripButton21_Text {
            get {
                return ResourceManager.GetString("toolStripButton21.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove from filtered 的本地化字符串。
        /// </summary>
        internal static string toolStripButton22_Text {
            get {
                return ResourceManager.GetString("toolStripButton22.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fing tag in \&quot;All tags\&quot; 的本地化字符串。
        /// </summary>
        internal static string toolStripButton23_Text {
            get {
                return ResourceManager.GetString("toolStripButton23.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter in all tags 的本地化字符串。
        /// </summary>
        internal static string toolStripButton24_Text {
            get {
                return ResourceManager.GetString("toolStripButton24.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove filter 的本地化字符串。
        /// </summary>
        internal static string toolStripButton25_Text {
            get {
                return ResourceManager.GetString("toolStripButton25.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string toolStripButton3_Text {
            get {
                return ResourceManager.GetString("toolStripButton3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Up 的本地化字符串。
        /// </summary>
        internal static string toolStripButton4_Text {
            get {
                return ResourceManager.GetString("toolStripButton4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Down 的本地化字符串。
        /// </summary>
        internal static string toolStripButton5_Text {
            get {
                return ResourceManager.GetString("toolStripButton5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change all tags/common tags 的本地化字符串。
        /// </summary>
        internal static string toolStripButton6_Text {
            get {
                return ResourceManager.GetString("toolStripButton6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add to all 的本地化字符串。
        /// </summary>
        internal static string toolStripButton7_Text {
            get {
                return ResourceManager.GetString("toolStripButton7.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace tag 的本地化字符串。
        /// </summary>
        internal static string toolStripButton8_Text {
            get {
                return ResourceManager.GetString("toolStripButton8.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy tags 的本地化字符串。
        /// </summary>
        internal static string toolStripButton9_Text {
            get {
                return ResourceManager.GetString("toolStripButton9.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open folder 的本地化字符串。
        /// </summary>
        internal static string toolStripMenuItem1_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete image and tags 的本地化字符串。
        /// </summary>
        internal static string toolStripMenuItem2_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate tags 的本地化字符串。
        /// </summary>
        internal static string translateTagsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("translateTagsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        internal static string viewToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("viewToolStripMenuItem.Text", resourceCulture);
            }
        }
    }
}
